### START JAVA 8
---
- file: path=/usr/lib/jvm state=directory

- get_url: url="http://download.oracle.com/otn-pub/java/jdk/8u71-b15/jdk-8u71-linux-x64.tar.gz" 
           dest=/usr/lib/jvm/jdk-8u71-linux-x64.tar.gz
           headers='Cookie:oraclelicense=accept-securebackup-cookie'
           force=no

- unarchive: src=/usr/lib/jvm/jdk-8u71-linux-x64.tar.gz
                 dest=/usr/lib/jvm
                 copy=no
                 creates=/usr/lib/jvm/jdk1.8.0_71

- command: 'alternatives --install "/usr/bin/java" "java" "/usr/lib/jvm/jdk1.8.0_71/bin/java" 2000'

- alternatives: name=java path=/usr/lib/jvm/jdk1.8.0_71/bin/java
### END JAVA 8