---
- yum: name=redis state=present

- name: copy configuration file
  template: >
      src=redis-sentinel.conf
      dest=/etc/redis-sentinel.conf
      owner=redis
      group=redis
      mode=0644


- lineinfile: dest=/etc/redis.conf regexp='^.* bind 127.0.0.1*' line='bind 0.0.0.0'

- service: name=redis state=restarted enabled=yes

- service: name="redis-sentinel" state=restarted enabled=yes
