#run: ansible-playbook ec2-provision.yml -u centos
- name: Configure instances
  hosts: tag_ansible_group_web, tag_ansible_group_loadbalancer
  remote_user: centos
  become: True
  gather_facts: True

  vars:

  tasks:
    - authorized_key: user=root key="{{ lookup('file', '/home/tobias.ericsson/.ssh/id_rsa.pub') }}"
    - selinux: state=disabled
    #- command: systemctl stop firewalld
    #- command: systemctl disable firewalld
    
    - name: install EPEL repo
      yum: name=epel-release state=present

    - name: Install packages
      yum: name={{ item }} state=present
      with_items:
        - curl
        - unzip
        - wget
        - nmap
        - firewalld

    - service: name=firewalld state=started
    - firewalld: service=https permanent=true state=enabled
    - firewalld: port=8080/tcp permanent=true state=enabled
    - firewalld: port=80/tcp permanent=true state=enabled
    - firewalld: port=6379/tcp permanent=true state=enabled
    - firewalld: port=5000/tcp permanent=true state=enabled
    - service: name=firewalld state=restarted

    - lineinfile: dest=/etc/hosts regexp='^.* {{ ansible_hostname }}.*' line='{{ ansible_all_ipv4_addresses[0] }} {{ ansible_hostname }}'

- name: Configure web-instances
  hosts: tag_ansible_group_web
  remote_user: centos
  become: True
  gather_facts: False
  roles:
     - { role: common, tags: common }
     - { role: java, tags: java }
     - { role: redis, tags: redis }
     - { role: spring-boot, tags: spring-boot }

- name: Configure loadbalancers
  hosts: tag_ansible_group_loadbalancer
  remote_user: centos
  become: True
  gather_facts: False
  roles:
     - nginx
