---
- name: copy .bashrc
  template: >
      src=bashrc
      dest=~/.bashrc
      mode=0722

- yum: name=vim state=present
- name: copy .vimrc
  template: >
      src=vimrc
      dest=~/.vimrc
      mode=0722

- name: copy hosts
  template: >
      src=hosts
      dest=/etc/hosts
      owner=root
      group=root
      mode=0644
